### ISSUE TITLE
Set the rewardInfo

### ISSUE THREAD

**Issue by mgolebiowski95** [pollfish/android-sdk-pollfish#13]
Hi, I have a little problem. I just testing your SDK. I init Pollfish with params: 

val params = Params.Builder(apiKey)
            .releaseMode(false)
            .rewardMode(true)
            .rewardInfo(RewardInfo("my_reward", 1.0)) // reward name
            .build()

But when I receive the survey in "onPollfishSurveyCompleted" callback the reward name is still "Points". Maybe it is why I test the app in the developer mode?

Section from documentation 5.3.1.9 "An object passing information during initialization regarding the reward settings, overriding the values as speciefied on the Publisher's Dashboard"

Parameter "rewardName" Overrides the reward name as specified in the Publisher's Dashboard.

But in my tests, it doesn't override the reward name.
![screen](https://user-images.githubusercontent.com/35255808/139080155-32f87ea1-05a3-41ae-8bfb-0be9bfcb699b.png)

**Comment by kaspanvo** [comment]
In order to receive the right reward name and exchange rate you need to include the relevant signature as specified in the docs in order to adjust in a secure way what you prompt to users. We would advice though if the reward name and exchange rate will not change often to specify the preferred ones on your Pollfish Dashboard in the App Settings area in the relevant integration approach (Rewarded Survey, Offerwall, JSON Offerwall). Please let me know if that helps.

**Comment by mgolebiowski95** [comment]
Hi, I added the signature but it still doesn't work for me. 

![poolfish](https://user-images.githubusercontent.com/35255808/139688518-3734b299-2ddf-4c57-bf12-35802d558f2d.png)

This is a sample project where I want to test this service (Poolfish) before I add this to the main project. But I've come to the conclusion that I don't need to set a reward name in the app.

**Comment by fotism23** [comment]
Hello @mgolebiowski95 
We have provided a fix regarding the issue you were facing in case you still want to use the Builder to set the reward name per request. Otherwise, you can continue using the dashboard approach which has the same effect.
